name: CI'
'
on: [push]'
'
jobs:'
  test:'
    runs-on: ubuntu-latest'
'
    steps:'
      - name: Izgūt repozitorija kodu'
        uses: actions/checkout@v4'
'
      - name: Iestatīt Python vidi'
        uses: actions/setup-python@v5'
        with:'
          python-version: "3.14"'
'
      - name: Palaist testus'
        run: python -m unittest discover'
